version: '3'
services:
    web:
        build: ./docker
        restart: always
        volumes:
            - .:/var/www/html
        environment:
            DEBUG: 'true'
            PHP_IDE_CONFIG: "serverName=_"
            XDEBUG_SESSION: '_'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - '81:8080'
        expose:
            - '81'
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'vtc-db'
            MYSQL_PASSWORD: 'root'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - '3307:3306'
        expose:
            - '3307'
        volumes:
            - vtc-db:/var/lib/mysql
volumes:
    vtc-db:
